# Generated by Django 3.0.11 on 2021-01-23 16:04

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210123_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
